spring:
  datasource:
    url: jdbc:mysql://localhost/jpadb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true